root: true
extends:
  - prettier
parser: "@babel/eslint-parser"
env: {}
globals: {}
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
